-- 연습문제 PDF PT.1
-- 1. 테이블생성
CREATE TABLE MY_DATA(
    ID NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(10),
    USERID VARCHAR2(30),
    SALARY NUMBER(10,2)
);

DESC MY_DATA;
SELECT * FROM MY_DATA;

INSERT INTO MY_DATA (ID, NAME, USERID, SALARY) VALUES (1, 'Scott', 'sscott', 10000);
INSERT INTO MY_DATA VALUES (2, 'Ford', 'fford', 13000);
INSERT INTO MY_DATA VALUES (3, 'Patel', 'ppatel', 33000);
INSERT INTO MY_DATA VALUES (4, 'Report', 'rreport', 23500);
INSERT INTO MY_DATA VALUES (5, 'Good', 'ggood', 44450);

SELECT ID, NAME, USERID, TO_CHAR(SALARY, '999,999.99') SALARY FROM MY_DATA;
COMMIT;

UPDATE MY_DATA SET SALARY = 65000 WHERE ID = 3;
COMMIT;
DELETE FROM MY_DATA WHERE NAME = 'Ford';
UPDATE MY_DATA SET SALARY = 15000 WHERE SALARY <= 15000;
DROP TABLE MY_DATA;
