DROP SEQUENCE CNO_SEQ;
CREATE SEQUENCE CNO_SEQ
    MAXVALUE 999
    NOCACHE
    NOCYCLE;

DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;
CREATE TABLE CUS_LEVEL (
    LEVELNO NUMBER(2),
    LEVELNAME VARCHAR2(9) NOT NULL,
    PRIMARY KEY(LEVELNO)
    );
INSERT INTO CUS_LEVEL (LEVELNO, LEVELNAME)
    VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL (LEVELNO, LEVELNAME)
    VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL (LEVELNO, LEVELNAME)
    VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL (LEVELNO, LEVELNAME)
    VALUES (4, 'BLACK');
SELECT * FROM CUS_LEVEL;

CREATE TABLE CUSTOMER (
    CNO NUMBER(2),
    CNAME VARCHAR2(20) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(20),
    POINT NUMBER(38),
    LEVELNO NUMBER(2),
    PRIMARY KEY(CNO),
    UNIQUE (PHONE),
    FOREIGN KEY(LEVELNO) REFERENCES CUS_LEVEL(LEVELNO)
    );
INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNO)
    VALUES (CNO_SEQ.NEXTVAL, 'È«±æµ¿', TO_DATE('21/06/10', 'RR/MM/DD'), '010-9999-9999', 0, 1);
INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNO)
    VALUES (CNO_SEQ.NEXTVAL, 'ÀÌÃ¶¼ö', '20/11/12', '010-8888-8888', NULL, 2);
SELECT * FROM CUSTOMER;
UPDATE CUSTOMER SET POINT = 300 WHERE CNAME = 'È«±æµ¿';
UPDATE CUSTOMER SET JOINDATE = '16/09/06' WHERE CNAME = 'ÀÌÃ¶¼ö';
UPDATE CUSTOMER SET PHONE = '010-9999-9888' WHERE CNAME = 'ÀÌÃ¶¼ö';

SELECT CNO cno, CNAME cname, TO_CHAR(JOINDATE, 'YYYY-MM-DD') joindate, PHONE phone, POINT point, LEVELNAME levelname
    FROM CUSTOMER, CUS_LEVEL
    WHERE CUSTOMER.LEVELNO = CUS_LEVEL.LEVELNO;
    
    
    